import { configureStore } from '@reduxjs/toolkit';
import { productApi } from './apis/productsApi';

const store = configureStore({

    reducer : {
        [productApi.reducerPath] : productApi.reducer
    },

    /**
     * middleware intercepts your requests and responses
     *      it is literally the middle point between when api call and our api endpoint
     * 
     *      catching errors, logging, crash reports
     *      
     *      cacheing
     *          rtk query will cache your data for you, and not make certain requests if you don't have to
     * 
     *      telling RTK Query to use the middleware generated by createApi in addition to its own default functionality
     */
    middleware : (defaultMiddleware) => defaultMiddleware().concat(productApi.middleware)

});

export default store;